---
# Local_route is the IP address of a well known server on your network, it
# is used to choose the right ip address (think of hosts that have multiple nics
# and IP addresses assigned to them) of the host running the Health Manager. Default
# value of nil, should work in most cases.
local_route: 127.0.0.1

# NATS message bus URI
mbus: nats://localhost:4222/
logging:
  level: debug
pid: /var/vcap/sys/run/healthmanager.pid

# This database is shared with the cloud controller.
database_environment: # replaces database.yml
  production:
    database: cloudcontroller
    host: localhost
    port: 5432
    encoding: utf8
    username: postgres
    password: postgres
    adapter: postgresql
    timeout: 2000
    template: template0 # Required for utf8 encoding
  development:
    adapter: sqlite3
    database: db/cloudcontroller.sqlite3 # sqlite3 paths are relative to CC root.
    encoding: utf8
  test:
    adapter: sqlite3
    database: db/test.sqlite3
    encoding: utf8
intervals:
  # Interval for collecting statistics about this cloudfoundry instance.
  # Amongst other things, data collected includes number of users, number of
  # applications and memory usage.
  database_scan:        60
  # Time to wait before starting analysis for stopped applications.
  droplet_lost:         30
  # Interval between scans for analysis of applications.
  droplets_analysis:    20
  # An application is deemed to be flapping if it is found to be in a crashed
  # state (after a restart following every crash) for more than "flapping_death"
  # number of times in an interval that is "flapping_timeout" long.
  flapping_death:        1
  flapping_timeout:    500

  #once instance is declared flapping, its restarts will be delayed,
  #starting with the value of min_restart_delay but not exceeding the
  #value of max_restart_delay
  min_restart_delay:    60
  max_restart_delay:   480

  #if total number of crashes exceeds this value, the attempts to
  #restart a flapping instance are stopped. Use -1 to never give up on
  #restarts
  giveup_crash_number:   4

  # Time to wait before trying to restart an application after a crash is
  # detected
  restart_timeout:      20
  # Time to wait before analyzing the state of an application that has been
  # started/restarted
  stable_state:         60

#number of start requests send each second (subject to EM timer limitations)
#default value is 50.
dequeueing_rate: 50

# Used for /healthz and /vars endpoints. If not provided random
# values will be generated on component start. Uncomment to use
# static values.
#status:
#  port: 34502
#  user: thin
#  password: thin
